- name: systemtools
  import_role:
    name: systemtools

- name: Postfix
  include_role:
    name: postfix-smarthost
  when: "postfix_relayhost is defined"

- include_tasks: repo.yml

- include_tasks: master.yml
  when: openitcockpit_instance == 'standalone' or openitcockpit_instance == 'master'

- include_tasks:  satellite.yml
  when: openitcockpit_instance == 'satellite'
