- block:
  - name: Postfix
    include_role: name=postfix-smarthost
    static: no
  when: "postfix_relayhost is defined"

- include: repo.yml
  static: no

- include: master.yml
  static: no
  when: openitcockpit_instance == 'standalone' or openitcockpit_instance == 'master'

- include:  satellite.yml
  static: no
  when: openitcockpit_instance == 'satellite'
