- name: APT | remove old openitcockpit repo key
  apt_key:
    id: A7D3EAFA
    state: absent

- name: APT | openitcockpit repo key
  apt_key:
    data: "{{openitcockpit_repository_key }}"

- name: APT | remove old openitcockpit repo
  apt_repository:
    repo: "{{ item }}"
    filename: openitcockpit
    state: absent
  with_items:
    - "deb https://packages.openitcockpit.com/repositories/{{ ansible_distribution_release }} {{ ansible_distribution_release }} main"
    - "deb https://apt.open-itcockpit.com trusty main"

- name: APT | openitcockpit repo
  apt_repository:
    repo: "deb https://secret:{{ openitcockpit_license }}@packages.openitcockpit.com/repositories/{{ ansible_distribution_release }} {{ ansible_distribution_release }} main"
    filename: "openitcockpit"
