- name: Fact | Repo
  set_fact:
    openitcockpit_repo: "deb https://packages.openitcockpit.io/openitcockpit/{{ ansible_distribution_release }}/stable {{ ansible_distribution_release }} main"
  when: not openitcockpit_repo is defined

- name: APT | remove old openitcockpit repo key
  apt_key:
    id: A7D3EAFA
    state: absent

- name: APT | openitcockpit repo key
  apt_key:
    data: "{{openitcockpit_repository_key }}"

- name: stat openitcockpit.list
  stat:
    path: /etc/apt/sources.list.d/openitcockpit.list
  register: openitcockpit_list_stat

# there are so many ways to add the openitcockpit repo... we try to keep the list file clean
- name: APT | remove old repos
  replace:
    dest: /etc/apt/sources.list.d/openitcockpit.list
    regexp: "^(?!((^\\s*#.*)|({{ openitcockpit_repo|regex_escape() }}))).*$"
  when: openitcockpit_list_stat.stat.exists

- name: APT | remove empty lines in openitcockpit.list
  lineinfile:
    path: /etc/apt/sources.list.d/openitcockpit.list
    state: absent
    regexp: "^$"

- name: APT | ensure auth.conf.d
  file:
    path: /etc/apt/auth.conf.d/
    state: directory

- name: APT | Set license
  lineinfile:
    line: "machine packages.openitcockpit.io login secret password {{openitcockpit_license}}"
    dest: /etc/apt/auth.conf.d/openitcockpit.conf
    create: yes
    mode: 0600
    owner: root
    group: root

- name: APT | openitcockpit repo
  apt_repository:
    repo: "{{ openitcockpit_repo }}"
    filename: "openitcockpit"
