- name: Fact | Repo protocol
  set_fact: openitcockpit_repo_protocol=http
  when: openitcockpit_package_cache is defined

- name: Fact | Repo
  set_fact:
    openitcockpit_repo: "deb {{ openitcockpit_repo_protocol }}://secret:{{ openitcockpit_license }}@packages.openitcockpit.com/repositories/{{ ansible_distribution_release }} {{ ansible_distribution_release }} main"

- name: APT | remove old openitcockpit repo key
  apt_key:
    id: A7D3EAFA
    state: absent

- name: APT | openitcockpit repo key
  apt_key:
    data: "{{openitcockpit_repository_key }}"

- name: APT | remove old repos
  replace:
    dest: /etc/apt/sources.list.d/openitcockpit.list
    regexp: "^(?!((^\s*#.*)|({{ openitcockpit_repo|regex_escape() }}))).*$"

- name: APT | openitcockpit repo
  apt_repository:
    repo: "{{ openitcockpit_repo }}"
    filename: "openitcockpit"
