- name: Fact | Naemon Packages
  set_fact:
    oitc_package_list:
      - openitcockpit-satellite
  when: openitcockpit_core == 'naemon'

- name: Fact | Nagios Packages
  set_fact:
    oitc_package_list:
      - openitcockpit-satellite
      - openitcockpit-nagios
  when: openitcockpit_core == 'nagios'

- name: Install nrpe module
  set_fact:
    oitc_package_list: "{{ oitc_package_list + ['nagios-nrpe-plugin'] }}"
  when: openitcockpit_module_nrpe

- name: Install nwc module
  set_fact:
    oitc_package_list: "{{ oitc_package_list + ['openitcockpit-nwc'] }}"
  when: openitcockpit_module_nwc

- name: Install check_mk module
  set_fact:
    oitc_package_list: "{{ oitc_package_list + ['openitcockpit-checkmk'] }}"
  when: openitcockpit_module_mk

- name: MySQL
  include_role:
    name: mysql

- name: createdb
  include_tasks: db.yml

- name: Installation
  apt:
    name: "{{ oitc_package_list }}"

- name: Create nagios ssh Folder
  file:
    path: /var/lib/nagios/.ssh
    owner: nagios
    group: nagios
    mode: "0700"
    state: directory

- name: Copy ssh pubkey
  lineinfile:
    dest: /var/lib/nagios/.ssh/authorized_keys
    line: "{{ lookup('file', openitcockpit_ssh_pubkey) }}"
    mode: "0644"
    owner: "nagios"
    group: "nagios"
    create: yes
  when: openitcockpit_ssh_pubkey is defined

- name: Create symlink for nrpe module
  file:
    path: /opt/openitc/nagios/libexec/check_nrpe
    state: link
    src: /usr/lib/nagios/plugins/check_nrpe
  when: openitcockpit_module_nrpe
